#!/bin/sh

SSH_KEY_TRAVIS_ID=a41cb2229a31

[ "$TRAVIS_BRANCH" = master ]

[ "$TRAVIS_PULL_REQUEST" = false ]

eval key=\$encrypted_${SSH_KEY_TRAVIS_ID}_key
eval iv=\$encrypted_${SSH_KEY_TRAVIS_ID}_iv

mkdir -p ~/.ssh
openssl aes-256-cbc -K $key -iv $iv -in scripts/id_rsa.enc -out ~/.ssh/id_rsa -d
chmod 600 ~/.ssh/id_rsa

git config user.name "doc upload bot"
git config user.email "nobody@example.com"

cargo doc &&
    echo '<meta http-equiv=refresh content=0;url=srttool/index.html>' > target/doc/index.html &&
    pip install --user ghp-import &&
    ghp-import -n target/doc &&
    git push -fq git@github.com:juggle-tux/srttool.git gh-pages
